version: '2'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8085:8080
      - 50000:50000
    container_name: jenkins_latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /usr/docker/volumes/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
